### ISSUE TITLE
Warning: Detected empty branch 'master', it'll be ignored

### ISSUE THREAD

**Issue by andygrunwald** [MetricsGrimoire/CVSAnalY#64] opened 2014-02-23 10:29 UTC
If you extract the test/input.tar.gz and start a analysis on this via cvsanaly2, the output says that the master branch is empty:

```
./cvsanaly2 --config-file ./config --db-database cvsanaly_before /Users/andygrunwald/Development/tmp/input
Parsing log for /Users/andygrunwald/Development/tmp/input (git)
Warning: Detected empty branch 'master', it'll be ignored
Executing extensions
Executing extension FileTypes
Executing extension Metrics
...
```

In my understanding a master branch can`t be empty if there are commits in it. Isn`t it?
Or i am wrong?

**Comment by shiona** [comment] 2014-04-08 06:02
We've come across the same error. In our case initial testing would suggest cvsanaly does not understand branches that have no head i.e. have been merged with --no-ff in git.

**Comment by andygrunwald** [comment] 2014-04-08 06:05
When does this happen?
If a branch is merged into master with `--no-ff`?
I does not understand the warning.
@shiona can you explain this more in detail?

**Comment by shiona** [comment] 2014-04-08 06:11
I will have to do some more testing before I can say anything definite about this. I'll try to recreate the problem with a simple repo.

**Comment by andygrunwald** [comment] 2014-04-08 06:31
@shiona You can reproduce it with out input.tar.gz from our test folder: https://github.com/MetricsGrimoire/CVSAnalY/blob/master/tests/input.tar.gz
This is such a repo which is 
- simple
- reproduce the warning

**Comment by mniemela** [comment] 2014-05-23 11:21
We have had this issue with CVSAnaly. I have been trying to read the source code from file GitParser.py where the warning seems to come from. It seems like there's some bug in if clause at row 169. However, there are few comments in the code, so I'd like to ask some questions.

1) What's self.branch? Is it the branch to which the last inspected commit belonged to?

2) What's branch? Is it the branch to which the currently inspected commit belongs to?

3) How should the if condition work in row 169? It looks like it tests if commit in git_commit is parent to commit in self.branch and if so, ignores the branch currently being inspected. I tested the test repository behind the link and added some test prints to the file, and apparently git_commit refers to commit 589bb080f059834829a2a5955bebfd7c2baa110a when CVSAnaly gives warning "Warning: Detected empty branch 'master', it'll be ignored". This seems to be just before a new branch is created.

**Comment by sduenas** [comment] 2014-06-03 16:47
Sorry for my late response but I didn't have much time until today to check this problem. I've been working on this during the morning and these are my conclusions:
- An **empty branch** is a branch that has been fully merged into other branch. This means that all the commits from that branch were merged into an active branch.
  For example, think on a topic branch to fix an issue. You make a new branch, work on this branch and when the problem is fixed, you merge the topic branch into master. If you don't delete the branch from the repo, the branch is still there but is inactive and it doesn't have any new commits. CVSAnalY ignores these branches to avoid inserting the same commit more than once in the database.
  The problem here is that 'empty' is not an accurate term. It doesn't describe well what the branch really is. My opinion is we have to change 'empty' to something more descriptive. I don't know if 'inactive' or 'deprecated' work better...
- Regarding the code, @mniemela, you're right.  `self.branch` is the branch to which the last inspected commit belonged to, and `branch` is the branch of the current parsed commit.
- I don't know if the problem with the test repo is a real problem or not. I'm almost sure the answer is a yes but I don't see how to fix it. The thing is as follows:
  The test repository has to `master` branches:  `refs/heads/master`that is a local branch and `refs/remotes/origin/master` that is a remote branch. When the parser reaches commit `589bb08`, it has been analyzing the local branch. It reaches there and sees that `589bb08` commit is the HEAD of another branch. In this case, the HEAD of the remote branch. It checks  whether the commit is the ancestor of the current branch (the local branch) and yes, it is. So, as this commit is the HEAD of the remote branch but it is the ancestor  of the local branch, CVSAnalY thinks that the remote branch was fully merged into the local one, setting the remote as an empty branch. `master` is analyzed not the remote branch but the local one.

Comments?

**Comment by mniemela** [comment] 2014-06-04 09:33
Hi,

Yes, it does look like the branch CVSAnaly is ignoring is the remote master rather than local master. It's a good question if that's actually a problem, and honestly I have no idea. At least 'deprecated' would be a less confusing word than 'empty.

Anyways, when I did the same git operations to the test repository as what we talked about in IRC. It looks like when two branches' HEAD points to same commit, it ignores one of them. Apparently this made it ignore branch 'master' rather branch 'test', which is probably quite confusing.

-Mikael

**Comment by mniemela** [comment] 2014-06-06 07:32
Hi again,

We have noticed some other errors, for example in extensions/FileRevs.py error CommandError is not imported even though it's used in line 95, should I import it and/or commit the fix somewhere?

Then there are some problems with Metrics extension, for some reason I got this error when trying out Metrics with the same test repository:

Error obtaining bbb/something@c0d66f92a95e31c77be08dc9d0f11a16715d1885. Command ['git', 'show', u'c0d66f92a95e31c77be08dc9d0f11a16715d1885:bbb/something'] returned 128 (fatal: Path 'bbb/something' does not exist in 'c0d66f92a95e31c77be08dc9d0f11a16715d1885'
)

Also, when I tried it out with a large repository, it was tossing exceptions around.. I guess I'll read the Metrics code to try to understand what's going on there.

**Comment by jgbarah** [comment] 2014-06-06 07:50
Thanks a lot for the info. Would you mind opening separate tickets for each of these issues, so that we can focus on them one by one? In any case, of course if you submit a pull request for that CommandError thing, that's perfect, we will review it asap.

**Comment by mniemela** [comment] 2014-06-06 08:56
Ok, I created a pull request about the CommandError thing and created this issue: 

https://github.com/MetricsGrimoire/CVSAnalY/issues/85

Sorry about posting about them here, I answered an email and didn't realize that it would be posted here. :P

**Comment by andygrunwald** [comment] 2014-06-09 14:38
Hey,

thanks for this good discussion.
I don`t know either if this a problem or not, but i agree @sduenas that "empty" is not the perfect term.
In git there are two arguments which are related to this problem:
- `git branch --merged`
- `git branch --no-merged`

Maybe we should not change the term only, but the whole sentence.
I created a PR (https://github.com/MetricsGrimoire/CVSAnalY/pull/86) to change the sentence from `Warning: Detected empty branch 'master', it'll be ignored` to `Info: Branch 'master' will be ignored, because it was already merged in an active one.` + i added some more comments to avoid further confusion.

Comments?

**Comment by sduenas** [comment] 2014-06-09 17:14
+1

**Closed as completed** 2014-08-09 14:04 UTC
Labels: bug
