### ISSUE TITLE
Error when running "Months" extension for more than one project in the same database

### ISSUE THREAD

**Issue by dicortazar** [MetricsGrimoire/CVSAnalY#4] opened 2012-09-15 15:13 UTC
Months extension basically takes the minimum and maximum date of a project and and insert a row per month (between that minimum and maximum).

However, when this extension is run for several repositories in the same database (imagine this is run for the list of projects at Metrics Grimoire) and the Months extension is run for all of them, a crash will be raised given that the extension will try to fill the months table over and over (one per project). Thus, there is a problem with the integrity of the Primary Key used (In most of the cases there is an overlap).

So, not sure if this should work in this way, or perhaps, clearly specify that this should be run only at the end of the analysis of the whole list of projects...

My perception is that the very extension should be aware of the previous existence (or not) of the table "months", and fill extra months if needed.

Comments?

**Comment by jgbarah** [comment] 2012-09-16 21:24
On Sat, 2012-09-15 at 08:13 -0700, Daniel Izquierdo wrote:

> Months extension basically takes the minimum and maximum date of a
> project and and insert a row per month (between that minimum and
> maximum).
> 
> However, when this extension is run for several repositories in the
> same database (imagine this is run for the list of projects at Metrics
> Grimoire) and the Months extension is run for all of them, a crash
> will be raised given that the extension will try to fill the months
> table over and over (one per project). Thus, there is a problem with
> the integrity of the Primary Key used (In most of the cases there is
> an overlap).
> 
> So, not sure if this should work in this way, or perhaps, clearly
> specify that this should be run only at the end of the analysis of the
> whole list of projects...
> 
> My perception is that the very extension should be aware of the
> previous existence (or not) of the table "months", and fill extra
> months if needed.
> 
> Comments?

When I wrote it, it was intended to be run _after_ all repositories had
been analyzed. However, it makes sense (and it is easy) to let it be run
in any moment, and just check whether the table exists and delete it
before refilling it, or just refill it...

If nobody oposes, I can do that easily.

## 

http://identi.ca/jgbarah            http://twitter.com/jgbarah

**Comment by jgbarah** [comment] 2012-09-21 09:18
Nobody oposes, so I will do the change.

**Comment by dicortazar** [comment] 2012-09-21 09:21
Thanks! :)

**Comment by dicortazar** [comment] 2012-10-20 14:09
Advances?

**Comment by andygrunwald** [comment] 2013-08-12 20:53
The change which was mentioned by @jgbarah was made in https://github.com/MetricsGrimoire/CVSAnalY/commit/f5150c12f7c8a35587321d47cce9ba3292186d28#pycvsanaly2/extensions/Months.py

See https://github.com/MetricsGrimoire/CVSAnalY/blob/master/pycvsanaly2/extensions/Months.py#L100

So i will close this ticket because this is solved.
If anyone of you, @jgbarah or @dicortazar disagree, please let me know and reopen it!
THX

**Closed as completed by andygrunwald** 2013-08-12 20:53 UTC
Labels: bug, question
