### ISSUE TITLE
CommitsLOCDet crashing

### ISSUE THREAD

**Issue by shiona** [MetricsGrimoire/CVSAnalY#72] opened 2014-03-28 07:02 UTC
I'm testing using CVSAnaly git repo as test environment. Using python 2.7.6 I get "TypeError: 'long' object is not iterable". I'm using extensions CommitsLOCDet, Metrics and FileTypes. 
Full log: http://pastebin.com/DMD7fbSm

**Comment by sduenas** [comment] 2014-04-01 10:00
I've been analyzing CVSAnalY repository, using HEAD version of the tool. I didn't find any problem. Can you confirm you are using CVSAnalY as repo test and which revision you are analyzing?

```
sduenas@Guybrush:/tmp/CVSAnalY$ cvsanaly2 -g -u xxxx -p xxxx -d  --extensions=CommitsLOCDet .
DBG: INSERT INTO repositories (id, uri, name, type) values (%s, %s, %s, %s)
Parsing log for . (git)
['git', 'log', '--all', '--topo-order', '--pretty=fuller', '--parents', '--name-status', '-M', '-C', '--decorate=full', '--remotes=origin']
DBG: Branch 'master' head at acommit 857e104d5205157f945fb75ae0f25d36841322c8
DBG: INSERT into _temp_log (rev, date, object) values (%s, %s, %s)
DBG: Branch 'ninka' head at acommit ae0021132598a3e546c7a84b389573cb1c82ec61
DBG: Start point of branch 'ninka' at commit da58e532bc8b14f705b4f20c0266bb9bc94c1a82
DBG: INSERT into _temp_log (rev, date, object) values (%s, %s, %s)
DBG: INSERT into _temp_log (rev, date, object) values (%s, %s, %s)
DBG: Branch 'gh-pages' head at acommit bf1dfcf3c34da910cc38d9e8dcb4565a866bbd02
...
...
...
DBG: INSERT INTO actions (id, type, file_id, commit_id, branch_id) values (%s, %s, %s, %s, %s)
DBG: INSERT INTO scmlog (id, rev, committer_id, author_id, date, author_date, message, composed_rev, repository_id) values (%s, %s, %s, %s, %s, %s, %s, %s, %s)
DBG: DBContentHandler: Saving caches to disk (/home/sduenas/.cvsanaly2/cache/https:__github.com_MetricsGrimoire_CVSAnalY.git)
Executing extensions
Executing extension CommitsLOCDet
```

```
mysql> show tables like "%commits%";
+--------------------------+
| Tables_in_c2 (%commits%) |
+--------------------------+
| commits_files_lines      |
| commits_lines            |
+--------------------------+
2 rows in set (0.00 sec)
mysql> select * from commits_lines limit 10;
+----+-----------+-------+---------+
| id | commit_id | added | removed |
+----+-----------+-------+---------+
|  1 |         1 |   300 |       5 |
|  2 |         2 |    14 |       1 |
|  3 |         3 |   211 |       5 |
|  4 |         4 |    34 |      16 |
|  5 |         5 |    24 |       3 |
|  6 |         6 |    32 |       1 |
|  7 |         7 |    62 |      12 |
|  8 |         8 |     8 |       1 |
|  9 |         9 |     7 |       1 |
| 10 |        10 |    12 |       2 |
+----+-----------+-------+---------+
10 rows in set (0.00 sec)

```

**Comment by shiona** [comment] 2014-04-03 13:54
Yes, I'm using this repo as testing material

Back when I reported this I was 
d86c4496f33deb90e6f2f40f9fa01b5e8fddb1b8
now I tried (which to my understanding is the HEAD at the moment):
857e104d5205157f945fb75ae0f25d36841322c8 
and got the same error as before.

Both versions were their own test subject.

**Comment by sduenas** [comment] 2014-04-03 15:31
I've just updated the code of CommitsLOCDet extension. Can you try it again? Your problem should be fixed now. It was related with the version of MySQLdb you are using.

**Comment by shiona** [comment] 2014-04-03 15:48
Worked like charm. Thank you!
The change you made seems very strange.
Is there a bug in the version of my mysqldb or is that how it is intended to work?

**Comment by sduenas** [comment] 2014-04-03 16:17
No, it is not a bug.
The problem was we were passing as argument to `execute` method a long object and not a sequence. Some versions of `MySQLdb` allow passing both (as mine) but others doesn't (as yours) because require a sequence.
I close this bug.

**Closed as completed by sduenas** 2014-04-03 16:17 UTC
Labels: bug
